steps:
  - name: "docker"
    args: ["docker", "build", "--build-arg", "VERSION=Emolga", "-t", "gcr.io/$PROJECT_ID/inspect", "-t", "gcr.io/$PROJECT_ID/inspect:emolga", "."]
  - name: "docker"
    args: ["docker", "build", "--build-arg", "VERSION=Komala", "-t", "gcr.io/$PROJECT_ID/inspect:komala", "."]
  - name: "docker"
    args: ["docker", "build", "--build-arg", "VERSION=Pumpkaboo", "-t", "gcr.io/$PROJECT_ID/inspect:pumpkaboo", "."]
  - name: "docker"
    args: ["docker", "build", "--build-arg", "VERSION=Togepi", "-t", "gcr.io/$PROJECT_ID/inspect:togepi", "."]

images:
  - "gcr.io/$PROJECT_ID/inspect" 
  - "gcr.io/$PROJECT_ID/inspect:emolga" 
  - "gcr.io/$PROJECT_ID/inspect:komala" 
  - "gcr.io/$PROJECT_ID/inspect:pumpkaboo"
  - "gcr.io/$PROJECT_ID/inspect:togepi" 
